### PR TITLE
Updated code to fix text overflow and inconsistencies

### LINKED ISSUE #107: List title overflow
Writing a big lengthy title will cause the text to escape the list component. 

Apply the fix from [here](https://github.com/rizwan171/trello-clone/pull/86)

### PR DESCRIPTION
**Pull request by nk711**
resolves #107

### CODE REVIEW

**Review by rizwan171 — CHANGES_REQUESTED** [review]
I've got a few concerns with these changes:
1. I'm not sure whether list title should be a text area. I think its fine if its just a oneline input and the user could use their arrow keys for longer titles
2. Because it's now a textarea, whenever you click the title, the list area around the title grows a bit. Before (I believe) this didnt happen. Note this happens whether its a single line or multi line title

**Comment by rizwan171** [comment]
@nk711 Ignore 2) in the above comment, It actually grows when you click the title on the main branch

**Comment by nk711** [comment]
Answering your questions:
 
 1. I'm not sure whether list title should be a text area. I think its fine if its just a oneline input and the user could use their arrow keys for longer titles
 
-   I referenced Trello for this, they used a text area for the list title. Implementing this was pretty straight forward! 

 2. Because it's now a textarea, whenever you click the title, the list area around the title grows a bit. Before (I believe) this didnt happen. Note this happens whether its a single line or multi line title

- No problem, very good spot. I did not notice this. This has now been updated so that the list area does not grow when the list title field is set as selected.  This was done by removing the padding and margins also the border class from the text field.

**Comment by rizwan171** [comment]
LGTM, thanks for the title fix

**Review by rizwan171 — APPROVED** [review]

**Pull request merged**
